# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9dc6e2118c21728d69f6d8e5425734f142ad70c610a1c8ec7b07b0713312a2985fdfc01f07dff781690331aa96085a476c844611a9c9c4061310b679035aa608

test:
  secret_key_base: 2e64c62ac040bbc24649c199a2f39b662f508d9a61bfef6e28271cb1f64d42457231496b03e4e1e99542f8220ee998d6fea1cbe517a9abf65d3f3bb0730eb76e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
